### 
# GET - LISTE TOUT LES PRODUITS
GET http://localhost:3000/products HTTP/1.1

###
# Get - RECUPERE LE PRODUIT AVEC
GET http://localhost:3000/products/pomme HTTP/1.1

###
# POST - ADD A NEW PRODUCT
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name": "banane",
    "quantity": 2
}

###
# DELETE - REMOVE QUANTITY PRODUCT
DELETE http://localhost:3000/products/banane?quantity=1 HTTP/1.1


###
# DELETE - REMOVE PRODUCT
DELETE http://localhost:3000/products/banane HTTP/1.1
